### ISSUE TITLE
After changing the password, the user remains in the 'Change Password' form instead of going to the account settings page

### ISSUE THREAD

**Issue by yardenshoham** [yardenshoham/coin-trend-notifier-website#55]

**Comment by Aviel212** [comment]
Will be added on next push.

**Comment by yardenshoham** [comment]
https://github.com/yardenshoham/coin-trend-notifier-website/blob/b2744154fc4c50d9368873ef2c17d7cac1eca6c2/src/components/Settings/ChangePassword/ChangePasswordForm.jsx#L55
There's a typo
